project_id = "amhpjsmubciahslghobw"

[functions.agent-autopay-monitor]
verify_jwt = false

[functions.notify-delivery-agents]
verify_jwt = false

[functions.mark-order-as-packed]
verify_jwt = false

[functions.qr-scan-order]
verify_jwt = true

[functions.qr-complete-delivery]
verify_jwt = true

[functions.complete-delivery]
verify_jwt = true

[functions.complete-delivery-final]
verify_jwt = true

[functions.force-complete-delivery]
verify_jwt = true