// Legal content constants for Zaago Delivery Partner App
// Version tracking for consent management

export const LEGAL_VERSIONS = {
  privacy: '1.0',
  terms: '1.0',
  lastUpdated: '2024-12-27',
};

export const COMPANY_INFO = {
  name: 'Zaago',
  fullName: 'Zaago Delivery Services',
  supportEmail: 'helpzaago@gmail.com',
  supportPhone: '+91-7842343642',
  address: 'India',
  website: 'https://zaago.in',
};

export interface LegalSection {
  title: string;
  content: string[];
}

// ============================================
// PRIVACY POLICY CONTENT
// ============================================

export const PRIVACY_POLICY_SECTIONS: LegalSection[] = [
  {
    title: '1. Introduction & Scope',
    content: [
      `This Privacy Policy ("Policy") applies specifically to the Zaago Delivery Partner Application ("App") operated by ${COMPANY_INFO.fullName} ("Company", "we", "us", or "our"). This Policy governs the collection, use, storage, and disclosure of personal information from delivery agents ("Delivery Partner", "Agent", "you", or "your") who use our platform.`,
      'By registering as a Delivery Partner and using the App, you acknowledge that you have read, understood, and agree to be bound by this Privacy Policy.',
      'IMPORTANT: You are an independent contractor and NOT an employee of Zaago. This relationship is governed by the Terms & Conditions. This Policy covers only how we handle your personal data as an independent service provider on our platform.',
    ],
  },
  {
    title: '2. Definitions',
    content: [
      '• "Delivery Agent/Partner" means any individual who has registered on the Zaago platform to provide delivery services as an independent contractor.',
      '• "Platform" refers to the Zaago Delivery Agent Application, including all associated websites, mobile applications, and backend services.',
      '• "Customer" means end-users who place orders through the Zaago customer application.',
      '• "Seller/Merchant" means businesses that list their products on Zaago for sale to Customers.',
      '• "Admin" refers to Zaago\'s internal operations and management team.',
      '• "Personal Information" means any information that can identify you directly or indirectly.',
      '• "Sensitive Personal Data" includes financial information, identity documents, biometric data, and health information.',
    ],
  },
  {
    title: '3. Information We Collect',
    content: [
      '3.1 PERSONAL DETAILS:',
      '• Full legal name as per government ID',
      '• Mobile phone number (primary contact)',
      '• Email address',
      '• Profile photograph',
      '• Date of birth',
      '• Emergency contact information',
      '',
      '3.2 IDENTITY VERIFICATION DOCUMENTS:',
      '• Aadhaar Card (front and back)',
      '• Driving License (front and back)',
      '• PAN Card (for tax purposes)',
      '• Vehicle Registration Certificate (RC)',
      '• Insurance documents',
      '',
      '3.3 VEHICLE DETAILS:',
      '• Vehicle type (Bike, Scooter, Cycle, etc.)',
      '• Vehicle registration number',
      '• Vehicle make and model',
      '• Vehicle color',
      '• Driving license number and validity',
      '',
      '3.4 LOCATION DATA:',
      '• Real-time GPS location (foreground tracking)',
      '• Background location during active deliveries',
      '• Location history during online status',
      '• Last known location',
      '• Movement patterns and routes taken',
      '• Speed and heading information',
      '• Location accuracy data',
      '',
      '3.5 ORDER & DELIVERY DATA:',
      '• Orders accepted, rejected, and completed',
      '• Delivery timestamps (pickup, in-transit, delivered)',
      '• Distance traveled per delivery',
      '• Delivery duration and efficiency metrics',
      '• Delivery completion rate',
      '• Customer ratings and feedback',
      '• Delivery proof (photos, signatures, OTPs)',
      '',
      '3.6 EARNINGS & FINANCIAL DATA:',
      '• Bank account details (account number, IFSC, bank name)',
      '• UPI ID',
      '• Payout history and transaction records',
      '• Incentive and bonus earnings',
      '• Deductions and adjustments',
      '• Tax-related information',
      '',
      '3.7 DEVICE & TECHNICAL DATA:',
      '• Device ID and unique identifiers',
      '• Device make, model, and operating system',
      '• IP address and network information',
      '• App version and usage logs',
      '• Crash reports and error logs',
      '• Push notification tokens',
      '• Battery level and connectivity status',
      '',
      '3.8 COMMUNICATION DATA:',
      '• In-app messages with support',
      '• Call logs between agent and customer (masked numbers)',
      '• Support ticket history',
      '• Feedback and reviews submitted',
    ],
  },
  {
    title: '4. Purpose of Data Collection & Usage',
    content: [
      'We collect and process your personal information for the following purposes:',
      '',
      '4.1 ORDER MANAGEMENT:',
      '• Assigning delivery orders based on your proximity to pickup location',
      '• Displaying available orders within your service radius',
      '• Optimizing delivery routes for efficiency',
      '• Real-time tracking and ETA calculation',
      '',
      '4.2 EARNINGS & PAYOUTS:',
      '• Calculating per-delivery payouts based on distance',
      '• Processing incentives, bonuses, and surge pricing',
      '• Applying deductions for cancellations or penalties',
      '• Processing bank transfers and settlements',
      '• Generating earnings reports and tax statements',
      '',
      '4.3 IDENTITY VERIFICATION & COMPLIANCE:',
      '• Verifying your identity and eligibility to work',
      '• Validating driving license and vehicle documents',
      '• KYC compliance as per RBI and government regulations',
      '• Background verification for safety purposes',
      '',
      '4.4 PERFORMANCE MONITORING:',
      '• Tracking acceptance rate, completion rate, and ratings',
      '• Identifying areas for improvement',
      '• Determining eligibility for incentive programs',
      '• Maintaining quality standards on the platform',
      '',
      '4.5 FRAUD PREVENTION & SECURITY:',
      '• Detecting GPS spoofing or location manipulation',
      '• Identifying fake deliveries or fraudulent claims',
      '• Preventing unauthorized account access',
      '• Investigating complaints and disputes',
      '',
      '4.6 CUSTOMER SUPPORT:',
      '• Resolving delivery issues and complaints',
      '• Facilitating communication with customers and sellers',
      '• Providing technical assistance',
      '',
      '4.7 LEGAL & REGULATORY COMPLIANCE:',
      '• Complying with tax laws and GST requirements',
      '• Responding to legal requests from authorities',
      '• Maintaining records as per applicable laws',
    ],
  },
  {
    title: '5. Location Tracking Disclosure',
    content: [
      'IMPORTANT: Location tracking is essential for the delivery service. By using the App, you consent to location tracking as described below:',
      '',
      '5.1 WHEN WE TRACK YOUR LOCATION:',
      '• Continuously while you are "Online" and available for orders',
      '• During active deliveries (from order acceptance to completion)',
      '• When the app is in the background during deliveries',
      '• Even when the app is minimized (for active delivery tracking)',
      '',
      '5.2 WHY WE NEED LOCATION:',
      '• To show you nearby available orders',
      '• To calculate distance-based eligibility (e.g., within 10 km of pickup)',
      '• To provide real-time tracking to customers',
      '• To calculate accurate delivery distances for payout',
      '• To verify delivery completion at correct addresses',
      '• To optimize route suggestions',
      '',
      '5.3 LOCATION ACCURACY:',
      '• We use GPS, Wi-Fi, and cellular network data for accurate positioning',
      '• Inaccurate location may result in order assignment issues',
      '• GPS tampering or spoofing is strictly prohibited and may result in permanent deactivation',
      '',
      '5.4 TURNING OFF LOCATION:',
      '• You may go "Offline" to stop receiving orders (location still tracked minimally)',
      '• Completely disabling location will prevent order visibility and may affect your account',
      '• During active deliveries, location cannot be disabled',
    ],
  },
  {
    title: '6. Data Sharing & Disclosure',
    content: [
      'We may share your information with the following parties:',
      '',
      '6.1 WITH CUSTOMERS:',
      '• Your first name and profile photo',
      '• Real-time location during delivery',
      '• Estimated time of arrival (ETA)',
      '• Vehicle type and number (partial)',
      '',
      '6.2 WITH SELLERS/MERCHANTS:',
      '• Your name and contact (masked number)',
      '• Delivery status and estimated pickup time',
      '• Order-related information only',
      '',
      '6.3 WITH ZAAGO ADMIN & OPERATIONS:',
      '• Full profile and document information',
      '• Complete delivery and performance history',
      '• Earnings and payout records',
      '• Compliance and investigation data',
      '',
      '6.4 WITH THIRD-PARTY SERVICE PROVIDERS:',
      '• Map services (Google Maps, Mapbox) for navigation',
      '• Payment processors (Razorpay, banks) for payouts',
      '• Push notification services (OneSignal, FCM)',
      '• Cloud storage providers for document storage',
      '• Analytics services for app improvement',
      '',
      '6.5 LEGAL DISCLOSURES:',
      '• To comply with court orders or legal processes',
      '• To law enforcement agencies when legally required',
      '• To government authorities for regulatory compliance',
      '• To protect rights, safety, or property of Zaago or others',
    ],
  },
  {
    title: '7. Data Security',
    content: [
      'We implement robust security measures to protect your personal information:',
      '',
      '• Encryption: All data transmitted is encrypted using TLS/SSL protocols',
      '• Access Controls: Role-based access with multi-factor authentication',
      '• Secure Storage: Data stored on secure cloud servers with encryption at rest',
      '• Regular Audits: Periodic security assessments and vulnerability testing',
      '• Incident Response: Established procedures for handling data breaches',
      '• Employee Training: Staff trained on data protection and privacy',
      '',
      'While we take all reasonable precautions, no system is 100% secure. You are responsible for keeping your account credentials confidential.',
    ],
  },
  {
    title: '8. Data Retention',
    content: [
      'We retain your personal information as follows:',
      '',
      '• Active Account Data: Retained while your account is active',
      '• Order History: Retained for 7 years for audit and legal purposes',
      '• Financial Records: Retained for 8 years as per tax regulations',
      '• Identity Documents: Retained for 5 years after account deactivation',
      '• Location Data: Real-time location deleted after 90 days; summarized data retained longer',
      '• Communication Records: Retained for 3 years for dispute resolution',
      '',
      'Upon account deletion request, we will delete or anonymize your data within 90 days, except where retention is required by law.',
    ],
  },
  {
    title: '9. Your Rights',
    content: [
      'As a Delivery Partner, you have the following rights:',
      '',
      '9.1 ACCESS:',
      '• View and download your personal data from the app',
      '• Request a copy of all data we hold about you',
      '',
      '9.2 CORRECTION:',
      '• Update your profile information',
      '• Request correction of inaccurate data',
      '',
      '9.3 DELETION:',
      '• Request deletion of your account and personal data',
      '• Note: Some data may be retained for legal compliance',
      '',
      '9.4 OPT-OUT:',
      '• Unsubscribe from promotional communications',
      '• Disable non-essential notifications',
      '',
      '9.5 PORTABILITY:',
      '• Request your data in a machine-readable format',
      '',
      'To exercise these rights, contact us at: ' + COMPANY_INFO.supportEmail,
    ],
  },
  {
    title: '10. Cookies & Tracking Technologies',
    content: [
      'The App may use cookies, local storage, and similar technologies for:',
      '• Maintaining your login session',
      '• Remembering your preferences',
      '• Analyzing app usage and performance',
      '• Improving user experience',
      '',
      'You can manage these through your device settings, but disabling them may affect app functionality.',
    ],
  },
  {
    title: '11. Children\'s Privacy',
    content: [
      'The Zaago Delivery Partner App is not intended for individuals under 18 years of age. We do not knowingly collect personal information from minors. If you are under 18, you are not permitted to register as a Delivery Partner.',
    ],
  },
  {
    title: '12. Changes to This Policy',
    content: [
      'We may update this Privacy Policy from time to time. When we make changes:',
      '• We will notify you through the App or via email',
      '• The updated policy will be posted with a new "Last Updated" date',
      '• Continued use of the App after changes constitutes acceptance',
      '',
      'We encourage you to review this Policy periodically.',
    ],
  },
  {
    title: '13. Contact Information',
    content: [
      'For any privacy-related queries, concerns, or complaints:',
      '',
      `Email: ${COMPANY_INFO.supportEmail}`,
      `Phone: ${COMPANY_INFO.supportPhone}`,
      '',
      'Grievance Officer: Zaago Support Team',
      `Email: ${COMPANY_INFO.supportEmail}`,
      '',
      `Address: ${COMPANY_INFO.address}`,
    ],
  },
];

// ============================================
// TERMS & CONDITIONS CONTENT
// ============================================

export const TERMS_CONDITIONS_SECTIONS: LegalSection[] = [
  {
    title: '1. Eligibility Requirements',
    content: [
      'To register as a Delivery Partner on Zaago, you must meet the following criteria:',
      '',
      '1.1 AGE:',
      '• Minimum 18 years of age',
      '• Valid proof of age (Aadhaar Card, PAN Card, etc.)',
      '',
      '1.2 LEGAL AUTHORIZATION:',
      '• Legally authorized to work in India',
      '• No pending criminal cases or history of serious offenses',
      '',
      '1.3 REQUIRED DOCUMENTS:',
      '• Valid Aadhaar Card',
      '• Valid Driving License (for motorized vehicles)',
      '• Vehicle Registration Certificate (RC)',
      '• Vehicle Insurance (valid and up-to-date)',
      '• PAN Card (for tax purposes)',
      '',
      '1.4 VEHICLE REQUIREMENTS:',
      '• Own or have authorized access to a delivery vehicle',
      '• Vehicle in good working condition',
      '• Compliance with local traffic and pollution norms',
      '',
      '1.5 SMARTPHONE REQUIREMENTS:',
      '• Smartphone with GPS and internet capability',
      '• Ability to run the Zaago Delivery Agent App',
    ],
  },
  {
    title: '2. Nature of Relationship',
    content: [
      'IMPORTANT - PLEASE READ CAREFULLY:',
      '',
      '2.1 INDEPENDENT CONTRACTOR STATUS:',
      '• You are an INDEPENDENT CONTRACTOR and NOT an employee of Zaago',
      '• There is no employer-employee relationship between you and Zaago',
      '• You are not entitled to employment benefits, salary, insurance, or allowances from Zaago',
      '',
      '2.2 NO EXCLUSIVITY:',
      '• You are free to work with other delivery or logistics platforms',
      '• Zaago does not require exclusivity of services',
      '• You set your own working hours and availability',
      '',
      '2.3 SELF-EMPLOYMENT:',
      '• You are responsible for your own taxes, including GST if applicable',
      '• You must maintain your own vehicle, insurance, and equipment',
      '• Any liability for accidents, injuries, or damages is your responsibility',
      '',
      '2.4 NO GUARANTEED INCOME:',
      '• Zaago does not guarantee any minimum number of orders',
      '• Earnings depend on your availability, location, and demand',
      '• Incentives and bonuses are at Zaago\'s discretion and may change',
    ],
  },
  {
    title: '3. Account Registration & Verification',
    content: [
      '3.1 ACCURACY OF INFORMATION:',
      '• All information provided during registration must be accurate and complete',
      '• You must promptly update any changes to your personal or vehicle information',
      '• Uploading false, fraudulent, or expired documents is strictly prohibited',
      '',
      '3.2 VERIFICATION PROCESS:',
      '• Your documents will be verified before account activation',
      '• Zaago may conduct background verification',
      '• Approval is at Zaago\'s sole discretion',
      '• Rejection reasons may not be disclosed in all cases',
      '',
      '3.3 ACCOUNT SECURITY:',
      '• You are responsible for maintaining confidentiality of your login credentials',
      '• Do not share your account with others',
      '• Notify Zaago immediately if you suspect unauthorized access',
      '',
      '3.4 CONSEQUENCES OF FALSE INFORMATION:',
      '• Immediate account suspension or termination',
      '• Forfeiture of pending earnings',
      '• Legal action if warranted',
      '• Reporting to relevant authorities',
    ],
  },
  {
    title: '4. Order Visibility & Acceptance',
    content: [
      '4.1 ORDER ASSIGNMENT:',
      '• Orders are shown based on proximity to pickup location',
      '• Your online status and availability affect order visibility',
      '• Performance metrics (ratings, acceptance rate) may influence order priority',
      '',
      '4.2 VOLUNTARY ACCEPTANCE:',
      '• Acceptance of any order is voluntary',
      '• You may decline orders without providing reasons',
      '• However, excessive rejections may affect your performance score',
      '',
      '4.3 NO GUARANTEE:',
      '• Zaago does not guarantee any minimum number of orders',
      '• Order volume depends on customer demand, location, time, and competition',
      '• Being online does not guarantee order assignments',
      '',
      '4.4 ORDER DETAILS:',
      '• Pickup and delivery addresses are shown before acceptance',
      '• Estimated distance and payout are displayed',
      '• Special instructions from customers/sellers are provided',
    ],
  },
  {
    title: '5. Order Fulfillment Responsibilities',
    content: [
      'Upon accepting an order, you agree to:',
      '',
      '5.1 TIMELY SERVICE:',
      '• Proceed to the pickup location promptly',
      '• Collect the order items carefully',
      '• Deliver to the customer within the estimated time',
      '',
      '5.2 SAFE HANDLING:',
      '• Handle all items with care to prevent damage',
      '• Use appropriate bags for food items',
      '• Ensure items are not tampered with',
      '• Maintain proper temperature for perishable items',
      '',
      '5.3 PROFESSIONAL BEHAVIOR:',
      '• Be polite and respectful to customers, sellers, and Zaago staff',
      '• Wear clean and appropriate attire',
      '• Avoid arguments or confrontations',
      '• Follow customer delivery instructions',
      '',
      '5.4 DELIVERY VERIFICATION:',
      '• Verify customer identity as required',
      '• Collect OTP or signature for confirmation',
      '• Take delivery proof photos when required',
      '• Handle COD (Cash on Delivery) amounts correctly',
      '',
      '5.5 COMMUNICATION:',
      '• Keep the customer informed of delays',
      '• Use in-app calling features (masked numbers) for contact',
      '• Report issues to Zaago support promptly',
    ],
  },
  {
    title: '6. Location & Availability Rules',
    content: [
      '6.1 ONLINE/OFFLINE STATUS:',
      '• You control your availability by going Online or Offline',
      '• Being Online indicates you are ready to accept orders',
      '• You should only go Online when actually available to deliver',
      '',
      '6.2 LOCATION ACCURACY:',
      '• Ensure your device GPS is enabled and accurate',
      '• Poor location accuracy affects order assignments',
      '• Move to areas with better signal if needed',
      '',
      '6.3 GPS MANIPULATION PROHIBITED:',
      '• GPS spoofing, fake GPS apps, or location manipulation is STRICTLY PROHIBITED',
      '• Using VPNs or tools to alter location is forbidden',
      '• Detection of GPS tampering will result in IMMEDIATE PERMANENT DEACTIVATION',
      '• No warnings will be given for GPS fraud',
      '',
      '6.4 SERVICE AREAS:',
      '• Operate only within Zaago\'s designated service areas',
      '• You will receive orders based on your current location',
    ],
  },
  {
    title: '7. Earnings & Payments',
    content: [
      '7.1 PAYOUT STRUCTURE:',
      '• Earnings are calculated on a per-order basis',
      '• Base pay plus distance-based compensation',
      '• Rates may vary by time, location, and demand',
      '• Surge pricing may apply during peak hours',
      '',
      '7.2 INCENTIVES & BONUSES:',
      '• Zaago may offer incentives for completing targets',
      '• Bonus programs are at Zaago\'s discretion',
      '• Terms of incentive programs may change without notice',
      '• Incentives are subject to verification of eligible deliveries',
      '',
      '7.3 DEDUCTIONS:',
      '• Penalties for order cancellations after acceptance',
      '• Deductions for customer complaints or damages',
      '• COD settlement adjustments',
      '• Any applicable taxes or TDS',
      '',
      '7.4 SETTLEMENT:',
      '• Payouts are processed on a regular schedule (weekly/daily)',
      '• Payments are made to your registered bank account',
      '• COD amounts must be settled as per Zaago\'s policy',
      '• Holding COD amounts beyond the settlement window is prohibited',
      '',
      '7.5 DISPUTES:',
      '• Earnings disputes must be raised within 7 days',
      '• Provide relevant evidence for dispute resolution',
      '• Zaago\'s decision on disputes is final',
    ],
  },
  {
    title: '8. Cancellations & Penalties',
    content: [
      '8.1 AGENT-INITIATED CANCELLATION:',
      '• You may cancel an order before pickup in limited circumstances',
      '• Valid reasons: Customer unreachable, incorrect address, safety concerns',
      '• Excessive cancellations affect your performance score',
      '',
      '8.2 CANCELLATION PENALTIES:',
      '• Cancellation after pickup may result in penalties',
      '• Penalty amount depends on stage of delivery',
      '• Repeated cancellations may lead to suspension',
      '',
      '8.3 ORDER REASSIGNMENT:',
      '• Cancelled orders may be reassigned to other agents',
      '• You will not receive payout for cancelled orders',
      '',
      '8.4 CUSTOMER CANCELLATION:',
      '• If customer cancels, you may receive partial compensation',
      '• Return items to seller if required',
      '• Follow Zaago support instructions for cancelled orders',
    ],
  },
  {
    title: '9. Ratings & Performance',
    content: [
      '9.1 CUSTOMER RATINGS:',
      '• Customers rate your delivery service (1-5 stars)',
      '• Ratings reflect professionalism, timeliness, and behavior',
      '• Low ratings affect your performance score',
      '',
      '9.2 PERFORMANCE METRICS:',
      '• Acceptance Rate: Percentage of orders accepted vs. offered',
      '• Completion Rate: Percentage of orders delivered vs. accepted',
      '• On-Time Delivery Rate: Percentage of timely deliveries',
      '• Customer Rating: Average rating from customers',
      '',
      '9.3 IMPACT OF PERFORMANCE:',
      '• High performers may get priority order assignments',
      '• Low performers may see reduced order visibility',
      '• Very low ratings may result in account review or suspension',
      '• Performance metrics are reset periodically',
    ],
  },
  {
    title: '10. Prohibited Conduct',
    content: [
      'The following actions are strictly prohibited and may result in immediate account termination:',
      '',
      '10.1 FRAUD & DISHONESTY:',
      '• Fake deliveries or marking orders complete without delivery',
      '• Submitting false earnings claims',
      '• Creating multiple accounts',
      '• Manipulating ratings or reviews',
      '',
      '10.2 GPS & LOCATION FRAUD:',
      '• Using GPS spoofing apps or tools',
      '• Manipulating location data',
      '• Using VPNs to alter apparent location',
      '',
      '10.3 THEFT & TAMPERING:',
      '• Stealing items from orders',
      '• Tampering with or consuming food items',
      '• Opening sealed packages',
      '• Misappropriating COD payments',
      '',
      '10.4 HARASSMENT & MISCONDUCT:',
      '• Verbal or physical harassment of customers, sellers, or staff',
      '• Discriminatory behavior based on gender, religion, caste, etc.',
      '• Using abusive or threatening language',
      '• Stalking or contacting customers outside of deliveries',
      '',
      '10.5 SAFETY VIOLATIONS:',
      '• Delivering under influence of alcohol or drugs',
      '• Reckless driving or traffic violations',
      '• Carrying unauthorized passengers during deliveries',
      '',
      '10.6 PLATFORM ABUSE:',
      '• Sharing account credentials',
      '• Using unauthorized third-party apps',
      '• Exploiting system bugs or vulnerabilities',
      '• Colluding with others for fraudulent activities',
    ],
  },
  {
    title: '11. Suspension & Termination',
    content: [
      '11.1 TEMPORARY SUSPENSION:',
      '• Your account may be suspended pending investigation',
      '• Reasons: Customer complaints, document expiry, unusual activity',
      '• You will be notified of suspension and reason',
      '• Pending earnings may be held during suspension',
      '',
      '11.2 PERMANENT DEACTIVATION:',
      '• Account may be permanently deactivated for serious violations',
      '• GPS fraud, theft, harassment result in immediate deactivation',
      '• No prior warning for severe violations',
      '• Deactivation decision may be irreversible',
      '',
      '11.3 VOLUNTARY TERMINATION:',
      '• You may deactivate your account at any time',
      '• Pending earnings will be settled after deduction of dues',
      '• COD amounts must be settled before deactivation',
      '',
      '11.4 EFFECT OF TERMINATION:',
      '• Loss of access to the platform',
      '• Forfeiture of pending incentives',
      '• No liability on Zaago for income loss',
    ],
  },
  {
    title: '12. Insurance & Liability',
    content: [
      '12.1 AGENT\'S RESPONSIBILITY:',
      '• You are responsible for your own safety and that of your vehicle',
      '• Maintain valid vehicle insurance at all times',
      '• Personal accident insurance is recommended',
      '• Zaago is NOT responsible for accidents, injuries, or damages',
      '',
      '12.2 PLATFORM LIABILITY:',
      '• Zaago acts as an intermediary platform only',
      '• No liability for loss of income or business opportunities',
      '• No responsibility for vehicle breakdowns, theft, or damage',
      '• No liability for disputes between agent and customer/seller',
      '',
      '12.3 THIRD-PARTY CLAIMS:',
      '• You are liable for claims arising from your actions',
      '• Zaago is not responsible for third-party claims against you',
      '• You must indemnify Zaago against any such claims',
    ],
  },
  {
    title: '13. Intellectual Property',
    content: [
      '• The Zaago name, logo, and branding are owned by Zaago',
      '• The App and its content are protected by intellectual property laws',
      '• You may not copy, modify, or distribute any part of the App',
      '• Use of Zaago branding requires prior written consent',
      '• Any feedback or suggestions provided become Zaago\'s property',
    ],
  },
  {
    title: '14. Limitation of Liability',
    content: [
      'TO THE MAXIMUM EXTENT PERMITTED BY LAW:',
      '',
      '• Zaago is not liable for any indirect, incidental, or consequential damages',
      '• No liability for loss of profits, business, or data',
      '• Maximum liability limited to earnings from last 30 days',
      '• No guarantee of platform uptime or availability',
      '• Technical issues may affect service temporarily',
    ],
  },
  {
    title: '15. Indemnification',
    content: [
      'You agree to indemnify and hold harmless Zaago, its directors, officers, employees, and partners from any claims, losses, damages, liabilities, and expenses arising from:',
      '',
      '• Your use of the platform',
      '• Violation of these Terms',
      '• Violation of any third-party rights',
      '• Your negligence or misconduct',
      '• Accidents or injuries during deliveries',
      '• Legal claims from customers or sellers',
    ],
  },
  {
    title: '16. Governing Law & Jurisdiction',
    content: [
      '• These Terms are governed by the laws of India',
      '• Any disputes shall be subject to the exclusive jurisdiction of courts in India',
      '• Arbitration may be used for dispute resolution as per Arbitration and Conciliation Act, 1996',
      '• The language of proceedings shall be English or Hindi',
    ],
  },
  {
    title: '17. Force Majeure',
    content: [
      'Zaago shall not be liable for any failure or delay in performance due to:',
      '',
      '• Natural disasters (floods, earthquakes, etc.)',
      '• Pandemics or health emergencies',
      '• Wars, riots, or civil unrest',
      '• Government orders or restrictions',
      '• Network failures or cyber attacks',
      '• Any circumstances beyond reasonable control',
    ],
  },
  {
    title: '18. Modifications to Terms',
    content: [
      '• Zaago reserves the right to modify these Terms at any time',
      '• Changes will be notified through the App or email',
      '• Continued use after changes constitutes acceptance',
      '• If you disagree with changes, you may deactivate your account',
      '• Major changes will be highlighted for your attention',
    ],
  },
  {
    title: '19. Severability',
    content: [
      'If any provision of these Terms is found to be invalid or unenforceable, the remaining provisions shall continue in full force and effect. The invalid provision shall be modified to the minimum extent necessary to make it valid.',
    ],
  },
  {
    title: '20. Entire Agreement',
    content: [
      'These Terms, together with the Privacy Policy and any other policies referenced herein, constitute the entire agreement between you and Zaago regarding your use of the platform as a Delivery Partner.',
    ],
  },
  {
    title: '21. Contact Information',
    content: [
      'For any queries regarding these Terms & Conditions:',
      '',
      `Email: ${COMPANY_INFO.supportEmail}`,
      `Phone: ${COMPANY_INFO.supportPhone}`,
      '',
      `Address: ${COMPANY_INFO.address}`,
      '',
      'By registering as a Delivery Partner, you acknowledge that you have read, understood, and agree to be bound by these Terms & Conditions.',
    ],
  },
];
